### ISSUE TITLE
fetch-pack: protocol error: bad band #52

### ISSUE THREAD

**Issue by alexheretic** [w4/gitlab-cargo-shim#77]
After publishing a crate to the private registry clients started failing with this error. I see no error in the gitlab-cargo-shim server.

If I remove the new published crate it starts working again. There are ~260 releases in the repo.

```
fetch-pack: protocol error: bad band #52
fatal: protocol error: bad pack header
...

Caused by:
  Unable to update registry

Caused by:
  failed to fetch `ssh://gitlab-cargo-shim.local/org/crates`

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'ssh://gitlab-cargo-shim.local/org/crates/' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
```

I want to dig a bit deeper to try to reproduce exactly why this is happening. Any ideas? Like is there some size limit to the packfile being built?

**Comment by w4** [comment]
This potentially sounds like an issue with the framing in https://github.com/w4/packfile/blob/master/src/packet_line.rs - the size of the packfile could very well be overflowing the 4 hex digit byte marker (65535 bytes) and need chunking over multiple frames

**Comment by alexheretic** [comment]
Aha indeed, thanks for pointing out the code. Indeed looks like I am hitting this limit, as without the newer published crates I can see it close to u16::MAX.

```
[/home/alex/project/packfile/src/packet_line.rs:45:39] data_buf.len() + 4 = 64808
```

So chunking here means just multiple writes each with a 4-digit hex header under u16::MAX right? I'll give that a go.

**Comment by w4** [comment]
Yep, I would like to stream the packfile while it's being built at some point later on down the line but for now just breaking up the packet should be fine. I wonder if we could get a test similar to https://github.com/w4/packfile/blob/master/src/lib.rs#L40 but using `git fetch-pack` to test the codec. It looks like you might just be able to pass `--stateless-rpc` and then pass the packets via stdin, but I'm not entirely sure about that - feel free to leave it out if it's not easy.

**Comment by alexheretic** [comment]
https://github.com/w4/packfile/pull/3 has indeed fixed the issue :relieved:

**Comment by w4** [comment]
Thanks for the report & fix!
