### ISSUE TITLE
Optimise "first use" latency

### ISSUE THREAD

**Issue by alexheretic** [w4/gitlab-cargo-shim#81]
Caching significantly helps speedup packfile construction but, as they start empty, they are only effective after the first use.

This is particularly important to usage where a gitlab-cargo-shim server is spun locally up to handle a single task (how CI currently works at my company).

Some ideas:

## Persistent caches
Persistence config could be provided to the server to be read on startup, so the first use would be pre-cached. As the server operates it would continually update the persistent caches. ([alluded](https://github.com/w4/gitlab-cargo-shim/issues/75#issuecomment-1961072496))
- Q: What persistent cache/db to use?
- Q: How configurable should it be, will it be required or will in-memory caching still be supported?

## Provided cache snapshots
Allow passing in a cache snapshot as a startup argument/config. This would be used to populate the caches on startup, so the first use would be pre-cached. The server would otherwise continue to manage caches in-memory only.
- Q: What format would this use? (e.g. json? binary? compressed?)
- Q: How would the snapshots be created? (e.g. `gitlab-cargo-shim ... --create-cache-snapshot cache.json`, or perhaps the server just tries to save the latest caches to the fs on shutdown.)

**Comment by w4** [comment]
I've just pushed up my changes to main for the persistent cache - it will need a persistent volume on the host. Let me know how you get on with it https://github.com/w4/gitlab-cargo-shim/commit/b019baa44a052831150c9c5d04b45a8f015e39d6 cheers

**Comment by alexheretic** [comment]
b019baa44a052831150c9c5d04b45a8f015e39d6 is not a positive change for my use case.

~Firstly I'm having trouble building and running the project now, need to figure out the clang libstdc++ requirements.~ Fixed it now.

* The checksum cache has been replace, but now it caches checksums regardless of age. I'm not sure this is a good fit in general for the reasons detailed in #75.
* Hardcoded requirement on `metadata.json` regardless of `MetadataFormat` (I am using `JsonZst`)

**Comment by w4** [comment]
Hi Alex,

I updated the Dockerfile in https://github.com/w4/gitlab-cargo-shim/commit/dc1c88d83892abc90f66a7d10ae992a61c5fe4f6 to fix the missing clang dependency.

Regarding your other points:

- The checksum should never change as it would completely break any Cargo.locks using the dependency and the registry should be considered immutable even if Gitlab doesn't enforce that. However, if for whatever reason it does need to change, you can use the `bust-cache` command added in https://github.com/w4/gitlab-cargo-shim/commit/b819b9136de428d47082608c0918485ac80bd441
- The hardcoded requriement on `metadata.json` was an oversight when porting changes from my downstream repository. I will fix this now, sorry about that.

**Comment by w4** [comment]
The hardcoded `metadata.json` has been fixed in https://github.com/w4/gitlab-cargo-shim/commit/671b14c0edb3eec807f6efa091f0476b4277d7b0

**Comment by alexheretic** [comment]
> the registry should be considered immutable even if Gitlab doesn't enforce that

I totally agree. But I have had to delete and re-publish packages on occasion, but pretty much only shortly after publishing. Since in my case there can be many gitlab-cargo-shim servers running, dev running them locally etc it is quite difficult to manually "bust" each of the caches. That's why it was useful only caching older checksums. After a couple of days the likelihood we'd need to modify a package is close enough to zero.

So having `cache-releases-older-than = "2 days"` works really well for me. Also I wouldn't have a problem with the _default_ for this being zero.

**Comment by alexheretic** [comment]
With #82 rocksdb seems to work well for me and resolves this issue :+1:
